FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

COPY requirements/api.txt ./
RUN pip install --no-cache-dir -r api.txt

COPY api/ ./api/
COPY templates/ ./templates/

CMD ["python", "-m", "api.app.main"]
